create database amazonedb;
use amazonedb;
CREATE TABLE amazon_sales (
    Region VARCHAR(50),
    Country VARCHAR(50),
    Item_Type VARCHAR(50),
    Sales_Channel VARCHAR(20),
    Order_Priority VARCHAR(5),
    Order_Date DATE,
    Order_ID BIGINT,
    Ship_Date DATE,
    Units_Sold INT,
    Unit_Price FLOAT,
    Unit_Cost FLOAT,
    Total_Revenue FLOAT,
    Total_Cost FLOAT,
    Total_Profit FLOAT
);
select * from amazon_sales;
---------------------------------------------------------------------------------------------------------------
#Q1. What is the total revenue generated across all orders?

select round(sum(Total_Revenue),2)as Total_Revenue_across_all_orders from amazon_sales;

---------------------------------------------------------------------------------------------
#Q2.Which item type has generated the highest total profit?

SELECT 
    Item_Type,
    ROUND(SUM(Total_Revenue), 2) AS Total_Revenue_itemwise
FROM amazon_sales
GROUP BY Item_Type
ORDER BY Total_Revenue_itemwise DESC
LIMIT 1;

---------------------------------------------------------------------------------------------
#Q3. Which region contributes the most to overall revenue? Rank regions from highest to lowest.

select Region , round(Sum(Total_Revenue),2) as Total_regionwise_revenue from amazon_sales group by Region order by Total_regionwise_revenue desc;

---------------------------------------------------------------------------------------------------------------------
#Q4. What is the month-wise sales trend (total revenue per month)?

SELECT 
    MONTHNAME(Order_Date) AS Order_Month,
    Region,
    ROUND(SUM(Total_Revenue), 2) AS Month_Wise_Sales
FROM amazon_sales
GROUP BY 
    Order_Month, 
    Region
ORDER BY 
    Month_Wise_Sales Asc;

-----------------------------------------------------------------------------------------------
#Q5. What is the average shipping duration (in days), and which region has the highest delay?
 SELECT 
    Region,
    round(AVG(DATEDIFF(Ship_Date, Order_Date)),0) AS avg_shipping_time
FROM amazon_sales
GROUP BY Region
ORDER BY avg_shipping_time DESC;

--------------------------------------------------------------------------------------------------------------
#Q6.Which country has the highest number of units sold overall?

select Country,round(sum(Unit_Price),2) as Countrywise_Unit_sold from amazon_sales group by Country order by CountryWise_Unit_sold desc;

----------------------------------------------------------------------------------------------------------------------------------------------
#Q7.What is the profit margin (%) for each item type, and which is the most profitable category?

SELECT 
    Item_Type,
    ROUND((SUM(Total_Profit) / SUM(Total_Revenue)) * 100, 2) AS Profit_Percentage_Itemwise
FROM amazon_sales
GROUP BY Item_Type
ORDER BY Profit_Percentage_Itemwise DESC;

------------------------------------------------------------------------------------------------------
#Q8. Compare total revenue generated by Online vs Offline sales channels. Which performs better?


select distinct Sales_Channel, round(sum(Total_Revenue),2) as Online_vs_Offline from amazon_sales group by Sales_Channel order by Online_vs_Offline desc;

---------------------------------------------------------------------------------------------------------------------------------------------------------
#Q9.Identify the top 5 countries with the highest total profit.

Select Country, round(sum(Total_Profit),0) as Countrywise_Profit from amazon_sales  group by Country order by Countrywise_Profit asc limit 5;

-------------------------------------------------------------------------------------------------------------------------------------------------------

#Q10. Calculate the running total revenue month-over-month using window functions.

SELECT 
    DATE_FORMAT(Order_Date, '%Y-%m') AS Month,
    SUM(Total_Revenue) AS Monthly_Revenue,
    SUM(SUM(Total_Revenue)) OVER (
        ORDER BY DATE_FORMAT(Order_Date, '%Y-%m')
    ) AS Running_Total_Revenue
FROM amazon_sales
GROUP BY Month
ORDER BY Month;
---------------------------------------------------------------------------------------------